### ISSUE TITLE
QUESTION - How to check if this is working

### ISSUE THREAD

**Issue by mnazmi23** [InnoGE/laravel-policy-soft-cache#14]
Hi, I have installed this package in my project, and I habe followed the known issue section too.

my question is, how do I test if my policies has been cached? Using debugbar, on the homepage I had the 73 gates checked, then after refreshed/installing this package, it is still the same 73 gate calles.

is there some kind of technique that I can use to test if this package is working for me?

**Comment by jesseyvanofferen-4s** [comment]
I think [Laravel telescope](https://laravel.com/docs/11.x/telescope) is a nice tool to do such thing. It's easy to install and provides a lot of information for each request. Very usefull if you want more / better insights on your backend and how it's handling requests.

**Comment by geisi** [comment]
@mnazmi23 

This package only caches recurring Gate calls. So, if you call for example:

```PHP
$user->can('viewAny', Post::class);
```

For Following Policy:

```PHP
class PostPolicy {
public function viewAny():bool
   {
   ///... Your "slow" code
   }
}
```

If you call this Gate multiple times for the same user within your app then the slow code will only called once.

**Comment by mnazmi23** [comment]
> @mnazmi23
> 
> This package only caches recurring Gate calls. So, if you call for example:
> 
> ```
> $user->can('viewAny', Post::class);
> ```
> 
> For Following Policy:
> 
> ```
> class PostPolicy {
> public function viewAny():bool
>    {
>    ///... Your "slow" code
>    }
> }
> ```
> 
> If you call this Gate multiple times for the same user within your app then the slow code will only called once.

I see. That is nice so the total gates number are expected to be the same. Noted. Thank you for your explanation! I am keeping this package in my project.
