### ISSUE TITLE
Does it work with guest user policy?

### ISSUE THREAD

**Issue by ankurk91** [InnoGE/laravel-policy-soft-cache#2]
Hi,

https://github.com/InnoGE/laravel-policy-soft-cache/blob/77be650a2f83c4070aa744459d1b20f5d7016914/src/LaravelPolicySoftCacheServiceProvider.php#L39

It requires to have a Model

What about guest users?
https://laravel.com/docs/9.x/authorization#guest-users

**Comment by geisi** [comment]
Currently, this package does not support Guest Policies. We have never seen any real-world applications using this feature in a proper manner. If you need this feature feel free to open a PR.

**Comment by ankurk91** [comment]
Thanks, i got my answer
